const express = require('express');
const router = express.Router();
const LegalNotice = require('../models/LegalNotice');
const Notification = require('../models/Notification');
const { protect, authorize } = require('../middleware/auth');
const User = require('../models/User');

// @route   POST /api/legal-notices
// @desc    Admin manually sends a legal notice
// @access  Admin
router.post('/', protect, authorize('admin'), async (req, res) => {
    try {
        const { officerId, title, content, complaintId } = req.body;

        if (!officerId || !title || !content) {
            return res.status(400).json({ message: "officerId, title, and content are required." });
        }

        const officer = await User.findById(officerId);
        if (!officer || officer.role !== 'officer') {
            return res.status(404).json({ message: "Officer not found." });
        }

        const legalNotice = new LegalNotice({
            officerId,
            complaint: complaintId || null,
            title,
            content,
            isAutoGenerated: false,
            escalationLevel: 'Critical',
            status: 'Pending'
        });

        await legalNotice.save();

        // Notify officer
        await Notification.create({
            user: officerId,
            title: "⚠ Official Legal Notice Received",
            message: `You have received a legal notice: "${title}". Please review it in the Legal Notices section and respond promptly.`,
            type: "legal_notice",
            relatedComplaint: complaintId || null
        });

        res.status(201).json({ message: "Legal notice sent successfully.", legalNotice });
    } catch (err) {
        console.error("Send Legal Notice Error:", err);
        res.status(500).json({ message: "Server error." });
    }
});

// @route   GET /api/legal-notices/all
// @desc    Admin views all legal notices
// @access  Admin
router.get('/all', protect, authorize('admin'), async (req, res) => {
    try {
        const notices = await LegalNotice.find()
            .populate('officerId', 'name email department')
            .populate('complaint', 'complaintId category status')
            .populate('complainantId', 'name email')
            .sort({ createdAt: -1 });
        res.json({ notices });
    } catch (err) {
        console.error("Fetch All Legal Notices Error:", err);
        res.status(500).json({ message: "Server error." });
    }
});

// @route   GET /api/legal-notices/mine
// @desc    Officer views their legal notices
// @access  Officer
router.get('/mine', protect, authorize('officer'), async (req, res) => {
    try {
        const notices = await LegalNotice.find({ officerId: req.user._id })
            .populate('complaint', 'complaintId category status')
            .populate('complainantId', 'name email')
            .sort({ createdAt: -1 });
        res.json({ notices });
    } catch (err) {
        console.error("Fetch My Legal Notices Error:", err);
        res.status(500).json({ message: "Server error." });
    }
});

// @route   PUT /api/legal-notices/:id/respond
// @desc    Officer submits response to legal notice
// @access  Officer
router.put('/:id/respond', protect, authorize('officer'), async (req, res) => {
    try {
        const { response } = req.body;
        if (!response) return res.status(400).json({ message: "Response text is required." });

        const notice = await LegalNotice.findById(req.params.id).populate('complaint');
        if (!notice) return res.status(404).json({ message: "Legal notice not found." });
        if (notice.officerId.toString() !== req.user._id.toString()) {
            return res.status(403).json({ message: "Access denied." });
        }

        notice.officerResponse = response;
        notice.status = 'Responded';
        await notice.save();

        // Add to complaint history if linked
        if (notice.complaint) {
            notice.complaint.history.push({
                status: notice.complaint.status,
                changedBy: req.user._id,
                remarks: `[Legal Notice Response]: ${response}`
            });
            await notice.complaint.save();
        }

        // Notify admins
        const admins = await User.find({ role: 'admin' });
        for (const admin of admins) {
            await Notification.create({
                user: admin._id,
                type: 'concern_responded',
                title: `Officer Responded to Legal Notice`,
                message: `Officer ${req.user.name} responded to legal notice "${notice.title}".\nResponse: ${response}`,
                relatedComplaint: notice.complaint?._id || null
            });
        }

        res.json({ message: "Response submitted.", notice });
    } catch (err) {
        console.error("Officer Respond Legal Notice Error:", err);
        res.status(500).json({ message: "Server error." });
    }
});

// @route   PUT /api/legal-notices/:id/read
// @desc    Officer marks notice as read
// @access  Officer
router.put('/:id/read', protect, authorize('officer'), async (req, res) => {
    try {
        const notice = await LegalNotice.findById(req.params.id);
        if (!notice) return res.status(404).json({ message: "Not found." });
        if (notice.status === 'Pending') {
            notice.status = 'Read';
            await notice.save();
        }
        res.json({ message: "Marked as read.", notice });
    } catch (err) {
        res.status(500).json({ message: "Server error." });
    }
});

module.exports = router;
