const mongoose = require('mongoose');

const LegalNoticeSchema = new mongoose.Schema({
  officerId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  complaint: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Complaint',
    default: null
  },
  complainantId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    default: null
  },
  title: {
    type: String,
    required: true
  },
  content: {
    type: String,
    required: true
  },
  officerResponse: {
    type: String,
    default: ''
  },
  escalationLevel: {
    type: String,
    enum: ['Normal', 'Warning', 'Critical'],
    default: 'Critical'
  },
  isAutoGenerated: {
    type: Boolean,
    default: false
  },
  status: {
    type: String,
    enum: ['Pending', 'Delivered', 'Read', 'Responded'],
    default: 'Pending'
  }
}, {
  timestamps: true
});

module.exports = mongoose.model('LegalNotice', LegalNoticeSchema);
